name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  schedule:
    -
      cron: '30 1 * * *'

jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        name: 'Use Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      -
        name: 'Install Package'
        if: steps.cache.outputs.cache-hit != 'true'
        run: 'npm install abhijithvijayan/stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'npx github:abhijithvijayan/stargazed --username  "andgar2010" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "stargazed update by GitHub Actions Workflow" --sort'
