name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on: # rebuild any PRs and main branch changes
  pull_request:
    # branches: [ master ]
  push:
    branches:
      - main # [ master ]
  schedule:
    - cron: "30 0 * * 0"

jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Try bun
        run: |
          bun --version
          
      -
        name: 'Use Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      -
        name: 'Install corepack'
        run: 'npm i -g corepack'

      -
        name: 'Enabled yarn 2'
        run: 'yarn init -2'

      -
        name: 'Install Package'
        run: 'yarn add https://github.com/abhijithvijayan/stargazed'
        
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'yarn exec stargazed --username  "andgar2010" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "stargazed update by GitHub Actions Workflow" --sort'
