name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on: # rebuild any PRs and main branch changes
  pull_request:
    # branches: [ master ]
  push:
    branches:
      - main # [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        name: 'Use Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: 'Install Package'
        run: 'npm install --global abhijithvijayan/stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'stargazed --username  "andgar2010" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "stargazed update by GitHub Actions Workflow" --sort'
